### ISSUE TITLE
Incorrect padding in `writeSlice` / `readSlice`?

### ISSUE THREAD

**Issue by malcolmstill** [judofyr/zini#1]
In `src/utils.zig` we have the definition of `writeSlice` and `readSlice`:

```zig
pub fn writeSlice(w: anytype, arr: anytype) !void {
    const T = @TypeOf(arr[0]);
    try w.writeIntNative(u64, arr.len);
    const byte_len = arr.len * @sizeOf(T);
    if (byte_len == 0) return;
    try w.writeAll(@as([*]const u8, @ptrCast(&arr[0]))[0..byte_len]);
    // Make sure we're always at a 64-bit boundary.
    try w.writeByteNTimes(0, byte_len % @alignOf(u64));
}
```

```zig
pub fn readSlice(stream: *std.io.FixedBufferStream([]const u8), T: anytype) ![]const T {
    var r = stream.reader();
    var len = try r.readIntNative(u64);
    const byte_len = len * @sizeOf(T);
    if (byte_len == 0) return &[_]T{};
    const data = stream.buffer[stream.pos..][0..byte_len];
    stream.pos += byte_len;
    stream.pos += byte_len % @alignOf(u64);
    const cast_data: [*]const T = @ptrCast(@alignCast(&data[0]));
    return cast_data[0..len];
}
```

In both the read and write case there is, if I'm reading correctly, some calculation of padding such that all data is 8-byte aligned:
- In `writeSlice`, the array data is written and then we pad with `try w.writeByteNTimes(0, byte_len % @alignOf(u64));`
- In `readSlice`, the `stream.pos` is incremented by the `byte_len` and then padded with `stream.pos += byte_len % @alignOf(u64);`

However, in `Debug` and `ReleaseSafe` modes I'm seeing a panic on incorrect alignment (I can follow up with a minimal example) and I think it's because the padding should be something like `(@alignOf(u64) - (byte_len % @alignOf(u64))) % @alignOf(u64)` instead of `byte_len % @alignOf(u64)`, which is maybe clearer with a table of some example values:

`byte_len` | `byte_len % @alignOf(u64)` | `(@alignOf(u64) - (byte_len % @alignOf(u64))) % @alignOf(u64)`
-- | -- | --
0 | 0 | 0
1 | 1 | 7
2 | 2 | 6
3 | 3 | 5
4 | 4 | 4
5 | 5 | 3
6 | 6 | 2
7 | 7 | 1
8 | 0 | 0
9 | 1 | 7
... | ... | ...

**Comment by judofyr** [comment]
Oh, yes, that sounds like a bug.

> I can follow up with a minimal example

Could you write a Zig test for this? I'm assuming it should be quite easily reproducible by using a `[]u8`.

**Comment by malcolmstill** [comment]
@judofyr 
> Could you write a Zig test for this? I'm assuming it should be quite easily reproducible by using a []u8.

Can do.

Am I okay to put in initial PRs on this repo and on https://github.com/judofyr/parg to update to the latest version of zig...otherwise the tests will fail (or rather fail to build) given the GitHub workflow itself depends on zig master? I can also add an `addModule` to the `parg` `build.zig` so it can be installed via the recent zig package management stuff rather than the relative path.

**Comment by judofyr** [comment]
Please do! That would be lovely.

I thought I had scheduled CI to run every week on the latest version of Zig, but it seems to that Zini is missing it and Parg hasn’t run…
